// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/deployment/v1/msg.proto

package v1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgDepositDeployment deposits more funds into the deposit account
type MsgDepositDeployment struct {
	ID     DeploymentID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	Amount types.Coin   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount" yaml:"amount"`
	// Depositor pays for the deposit
	Depositor string `protobuf:"bytes,3,opt,name=depositor,proto3" json:"depositor" yaml:"depositor"`
}

func (m *MsgDepositDeployment) Reset()         { *m = MsgDepositDeployment{} }
func (m *MsgDepositDeployment) String() string { return proto.CompactTextString(m) }
func (*MsgDepositDeployment) ProtoMessage()    {}
func (*MsgDepositDeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5db5b4dd1de0f0c, []int{0}
}
func (m *MsgDepositDeployment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositDeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositDeployment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositDeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositDeployment.Merge(m, src)
}
func (m *MsgDepositDeployment) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositDeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositDeployment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositDeployment proto.InternalMessageInfo

func (m *MsgDepositDeployment) GetID() DeploymentID {
	if m != nil {
		return m.ID
	}
	return DeploymentID{}
}

func (m *MsgDepositDeployment) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *MsgDepositDeployment) GetDepositor() string {
	if m != nil {
		return m.Depositor
	}
	return ""
}

// MsgCreateDeploymentResponse defines the Msg/CreateDeployment response type.
type MsgDepositDeploymentResponse struct {
}

func (m *MsgDepositDeploymentResponse) Reset()         { *m = MsgDepositDeploymentResponse{} }
func (m *MsgDepositDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDepositDeploymentResponse) ProtoMessage()    {}
func (*MsgDepositDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5db5b4dd1de0f0c, []int{1}
}
func (m *MsgDepositDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositDeploymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositDeploymentResponse.Merge(m, src)
}
func (m *MsgDepositDeploymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositDeploymentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgDepositDeployment)(nil), "akash.deployment.v1.MsgDepositDeployment")
	proto.RegisterType((*MsgDepositDeploymentResponse)(nil), "akash.deployment.v1.MsgDepositDeploymentResponse")
}

func init() { proto.RegisterFile("akash/deployment/v1/msg.proto", fileDescriptor_d5db5b4dd1de0f0c) }

var fileDescriptor_d5db5b4dd1de0f0c = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x6b, 0xdb, 0x40,
	0x18, 0xc6, 0x25, 0xb5, 0x18, 0xac, 0x52, 0x28, 0xaa, 0x07, 0xdb, 0xd4, 0x77, 0xae, 0xda, 0xc1,
	0x4b, 0xef, 0x50, 0x3b, 0xd5, 0xd0, 0xa1, 0xaa, 0x16, 0x0f, 0x85, 0xa2, 0x0e, 0x81, 0x2c, 0x41,
	0xf6, 0x1d, 0xca, 0x61, 0x4b, 0xaf, 0xd0, 0x29, 0x06, 0x7f, 0x8b, 0xec, 0x59, 0xf2, 0x21, 0xf2,
	0x21, 0x3c, 0x9a, 0x4c, 0x99, 0x8e, 0x20, 0x2f, 0xc1, 0xa3, 0x3f, 0x41, 0xb0, 0x4e, 0x58, 0x09,
	0x78, 0xbb, 0xf7, 0x7e, 0xef, 0x9f, 0xe7, 0x79, 0x5f, 0x7b, 0x10, 0xcd, 0x23, 0x79, 0x49, 0x19,
	0xcf, 0x16, 0xb0, 0x4a, 0x78, 0x5a, 0xd0, 0xa5, 0x47, 0x13, 0x19, 0x93, 0x2c, 0x87, 0x02, 0x9c,
	0x8f, 0x15, 0x26, 0x0d, 0x26, 0x4b, 0xaf, 0xdf, 0x89, 0x21, 0x86, 0x8a, 0xd3, 0xc3, 0x4b, 0xa7,
	0xf6, 0x7b, 0x33, 0x90, 0x09, 0xc8, 0x0b, 0x0d, 0x74, 0x50, 0x23, 0xa4, 0x23, 0x3a, 0x8d, 0x24,
	0xa7, 0x4b, 0x6f, 0xca, 0x8b, 0xc8, 0xa3, 0x33, 0x10, 0x69, 0xcd, 0xbf, 0x9e, 0x12, 0xf1, 0x62,
	0x66, 0x95, 0xe5, 0xde, 0x58, 0x76, 0xe7, 0xaf, 0x8c, 0x03, 0x9e, 0x81, 0x14, 0x45, 0x70, 0xc4,
	0xce, 0x3f, 0xdb, 0x12, 0xac, 0x6b, 0x0e, 0xcd, 0xd1, 0xbb, 0xef, 0x9f, 0xc9, 0x09, 0xc5, 0xa4,
	0x49, 0x9e, 0x04, 0xfe, 0x60, 0xad, 0xb0, 0x51, 0x2a, 0x6c, 0x4d, 0x82, 0x9d, 0xc2, 0x96, 0x60,
	0x7b, 0x85, 0xdb, 0xab, 0x28, 0x59, 0x8c, 0x5d, 0xc1, 0xdc, 0xd0, 0x12, 0xcc, 0x09, 0xed, 0x56,
	0x94, 0xc0, 0x55, 0x5a, 0x74, 0xad, 0xaa, 0x6b, 0x8f, 0xd4, 0x7e, 0x0e, 0x0e, 0x48, 0xed, 0x80,
	0xfc, 0x01, 0x91, 0xfa, 0xf8, 0xd0, 0x6d, 0xa7, 0x70, 0x5d, 0xb0, 0x57, 0xf8, 0xbd, 0xee, 0xa5,
	0x63, 0x37, 0xac, 0x81, 0x73, 0x66, 0xb7, 0x99, 0x96, 0x0e, 0x79, 0xf7, 0xcd, 0xd0, 0x1c, 0xb5,
	0xfd, 0x9f, 0x3b, 0x85, 0x9b, 0xcf, 0xbd, 0xc2, 0x1f, 0x74, 0xe9, 0xf1, 0xcb, 0xbd, 0xbf, 0xfb,
	0xd6, 0xa9, 0x47, 0xff, 0x66, 0x2c, 0xe7, 0x52, 0xfe, 0x2f, 0x72, 0x91, 0xc6, 0x61, 0x53, 0x36,
	0x7e, 0xfb, 0x74, 0x8b, 0x0d, 0x17, 0xd9, 0x9f, 0x4e, 0x2d, 0x27, 0xe4, 0x32, 0x83, 0x54, 0x72,
	0xff, 0xd7, 0xba, 0x44, 0xe6, 0xa6, 0x44, 0xe6, 0x63, 0x89, 0xcc, 0xeb, 0x2d, 0x32, 0x36, 0x5b,
	0x64, 0x3c, 0x6c, 0x91, 0x71, 0xfe, 0x25, 0x06, 0xbd, 0x34, 0x46, 0x04, 0x50, 0xc9, 0xe6, 0x34,
	0x05, 0xc6, 0x5f, 0x5f, 0x63, 0xda, 0xaa, 0x6e, 0xf0, 0xe3, 0x39, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0x60, 0xcd, 0xe6, 0x30, 0x02, 0x00, 0x00,
}

func (m *MsgDepositDeployment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositDeployment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositDeployment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Depositor) > 0 {
		i -= len(m.Depositor)
		copy(dAtA[i:], m.Depositor)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Depositor)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgDepositDeploymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositDeploymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositDeploymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintMsg(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsg(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgDepositDeployment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovMsg(uint64(l))
	l = m.Amount.Size()
	n += 1 + l + sovMsg(uint64(l))
	l = len(m.Depositor)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func (m *MsgDepositDeploymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovMsg(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsg(x uint64) (n int) {
	return sovMsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgDepositDeployment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositDeployment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositDeployment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depositor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depositor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositDeploymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositDeploymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositDeploymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsg
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsg
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsg
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsg        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsg          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsg = fmt.Errorf("proto: unexpected end of group")
)
