// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/manifest/v2beta1/httpoptions.proto

package v2beta1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CORSConfig defines CORS configuration for HTTP services
type CORSConfig struct {
	AllowedOrigins   []string `protobuf:"bytes,1,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowedOrigins,omitempty" yaml:"allowedOrigins,omitempty"`
	AllowedMethods   []string `protobuf:"bytes,2,rep,name=allowed_methods,json=allowedMethods,proto3" json:"allowedMethods,omitempty" yaml:"allowedMethods,omitempty"`
	AllowedHeaders   []string `protobuf:"bytes,3,rep,name=allowed_headers,json=allowedHeaders,proto3" json:"allowedHeaders,omitempty" yaml:"allowedHeaders,omitempty"`
	ExposedHeaders   []string `protobuf:"bytes,4,rep,name=exposed_headers,json=exposedHeaders,proto3" json:"exposedHeaders,omitempty" yaml:"exposedHeaders,omitempty"`
	AllowCredentials bool     `protobuf:"varint,5,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allowCredentials,omitempty" yaml:"allowCredentials,omitempty"`
	MaxAge           uint32   `protobuf:"varint,6,opt,name=max_age,json=maxAge,proto3" json:"maxAge,omitempty" yaml:"maxAge,omitempty"`
}

func (m *CORSConfig) Reset()      { *m = CORSConfig{} }
func (*CORSConfig) ProtoMessage() {}
func (*CORSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa251bcf6bf1d0e, []int{0}
}
func (m *CORSConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CORSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CORSConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CORSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CORSConfig.Merge(m, src)
}
func (m *CORSConfig) XXX_Size() int {
	return m.Size()
}
func (m *CORSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CORSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CORSConfig proto.InternalMessageInfo

func (m *CORSConfig) GetAllowedOrigins() []string {
	if m != nil {
		return m.AllowedOrigins
	}
	return nil
}

func (m *CORSConfig) GetAllowedMethods() []string {
	if m != nil {
		return m.AllowedMethods
	}
	return nil
}

func (m *CORSConfig) GetAllowedHeaders() []string {
	if m != nil {
		return m.AllowedHeaders
	}
	return nil
}

func (m *CORSConfig) GetExposedHeaders() []string {
	if m != nil {
		return m.ExposedHeaders
	}
	return nil
}

func (m *CORSConfig) GetAllowCredentials() bool {
	if m != nil {
		return m.AllowCredentials
	}
	return false
}

func (m *CORSConfig) GetMaxAge() uint32 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

// BasicAuthConfig defines basic authentication configuration for HTTP services
type BasicAuthConfig struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" yaml:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" yaml:"password,omitempty"`
}

func (m *BasicAuthConfig) Reset()      { *m = BasicAuthConfig{} }
func (*BasicAuthConfig) ProtoMessage() {}
func (*BasicAuthConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa251bcf6bf1d0e, []int{1}
}
func (m *BasicAuthConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BasicAuthConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BasicAuthConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BasicAuthConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicAuthConfig.Merge(m, src)
}
func (m *BasicAuthConfig) XXX_Size() int {
	return m.Size()
}
func (m *BasicAuthConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicAuthConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BasicAuthConfig proto.InternalMessageInfo

func (m *BasicAuthConfig) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *BasicAuthConfig) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// ServiceExposeHTTPOptions
type ServiceExposeHTTPOptions struct {
	MaxBodySize uint32           `protobuf:"varint,1,opt,name=max_body_size,json=maxBodySize,proto3" json:"maxBodySize" yaml:"maxBodySize"`
	ReadTimeout uint32           `protobuf:"varint,2,opt,name=read_timeout,json=readTimeout,proto3" json:"readTimeout" yaml:"readTimeout"`
	SendTimeout uint32           `protobuf:"varint,3,opt,name=send_timeout,json=sendTimeout,proto3" json:"sendTimeout" yaml:"sendTimeout"`
	NextTries   uint32           `protobuf:"varint,4,opt,name=next_tries,json=nextTries,proto3" json:"nextTries" yaml:"nextTries"`
	NextTimeout uint32           `protobuf:"varint,5,opt,name=next_timeout,json=nextTimeout,proto3" json:"nextTimeout" yaml:"nextTimeout"`
	NextCases   []string         `protobuf:"bytes,6,rep,name=next_cases,json=nextCases,proto3" json:"nextCases" yaml:"nextCases"`
	Cors        *CORSConfig      `protobuf:"bytes,7,opt,name=cors,proto3" json:"cors,omitempty" yaml:"cors,omitempty"`
	BasicAuth   *BasicAuthConfig `protobuf:"bytes,8,opt,name=basic_auth,json=basicAuth,proto3" json:"basicAuth" yaml:"basicAuth"`
}

func (m *ServiceExposeHTTPOptions) Reset()      { *m = ServiceExposeHTTPOptions{} }
func (*ServiceExposeHTTPOptions) ProtoMessage() {}
func (*ServiceExposeHTTPOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa251bcf6bf1d0e, []int{2}
}
func (m *ServiceExposeHTTPOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ServiceExposeHTTPOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ServiceExposeHTTPOptions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ServiceExposeHTTPOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceExposeHTTPOptions.Merge(m, src)
}
func (m *ServiceExposeHTTPOptions) XXX_Size() int {
	return m.Size()
}
func (m *ServiceExposeHTTPOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceExposeHTTPOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceExposeHTTPOptions proto.InternalMessageInfo

func (m *ServiceExposeHTTPOptions) GetMaxBodySize() uint32 {
	if m != nil {
		return m.MaxBodySize
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetReadTimeout() uint32 {
	if m != nil {
		return m.ReadTimeout
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetSendTimeout() uint32 {
	if m != nil {
		return m.SendTimeout
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetNextTries() uint32 {
	if m != nil {
		return m.NextTries
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetNextTimeout() uint32 {
	if m != nil {
		return m.NextTimeout
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetNextCases() []string {
	if m != nil {
		return m.NextCases
	}
	return nil
}

func (m *ServiceExposeHTTPOptions) GetCors() *CORSConfig {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *ServiceExposeHTTPOptions) GetBasicAuth() *BasicAuthConfig {
	if m != nil {
		return m.BasicAuth
	}
	return nil
}

func init() {
	proto.RegisterType((*CORSConfig)(nil), "akash.manifest.v2beta1.CORSConfig")
	proto.RegisterType((*BasicAuthConfig)(nil), "akash.manifest.v2beta1.BasicAuthConfig")
	proto.RegisterType((*ServiceExposeHTTPOptions)(nil), "akash.manifest.v2beta1.ServiceExposeHTTPOptions")
}

func init() {
	proto.RegisterFile("akash/manifest/v2beta1/httpoptions.proto", fileDescriptor_5fa251bcf6bf1d0e)
}

var fileDescriptor_5fa251bcf6bf1d0e = []byte{
	// 711 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x95, 0x3d, 0x6f, 0xd3, 0x40,
	0x1c, 0xc6, 0xe3, 0xbe, 0xa4, 0xed, 0x95, 0xbe, 0x60, 0xf1, 0x62, 0x3a, 0xd8, 0xe9, 0x49, 0x88,
	0x48, 0x40, 0x22, 0x5a, 0x89, 0x81, 0x05, 0xea, 0x08, 0x29, 0x0c, 0x28, 0xc8, 0xcd, 0x80, 0x58,
	0xa2, 0x4b, 0x7c, 0xb5, 0x4f, 0x8d, 0x7d, 0x96, 0xef, 0xd2, 0x26, 0x9d, 0xf8, 0x08, 0x6c, 0x7c,
	0x10, 0xbe, 0x04, 0x63, 0xc7, 0x4e, 0x16, 0xa4, 0x5b, 0x26, 0xd4, 0x4f, 0x80, 0xce, 0xe7, 0xf8,
	0x25, 0x6e, 0xbb, 0x39, 0xcf, 0xf3, 0xe4, 0xf9, 0xfd, 0xcf, 0xbe, 0xb3, 0x41, 0x1d, 0x9d, 0x22,
	0xe6, 0x36, 0x3d, 0xe4, 0x93, 0x13, 0xcc, 0x78, 0xf3, 0xec, 0xa0, 0x8f, 0x39, 0x7a, 0xd3, 0x74,
	0x39, 0x0f, 0x68, 0xc0, 0x09, 0xf5, 0x59, 0x23, 0x08, 0x29, 0xa7, 0xea, 0x93, 0x38, 0xd9, 0x98,
	0x27, 0x1b, 0x49, 0x72, 0xef, 0x91, 0x43, 0x1d, 0x1a, 0x47, 0x9a, 0xe2, 0x4a, 0xa6, 0xe1, 0xbf,
	0x15, 0x00, 0x5a, 0x1d, 0xeb, 0xb8, 0x45, 0xfd, 0x13, 0xe2, 0xa8, 0x2e, 0xd8, 0x41, 0xc3, 0x21,
	0x3d, 0xc7, 0x76, 0x8f, 0x86, 0xc4, 0x21, 0x3e, 0xd3, 0x94, 0xda, 0x72, 0x7d, 0xc3, 0x7c, 0x3f,
	0x8b, 0x0c, 0x2d, 0xb1, 0x3a, 0xd2, 0x79, 0x45, 0x3d, 0xc2, 0xb1, 0x17, 0xf0, 0xc9, 0x4d, 0x64,
	0x18, 0x13, 0xe4, 0x0d, 0xdf, 0xc1, 0xbb, 0x12, 0xd0, 0xda, 0x2e, 0x5a, 0x79, 0x92, 0x87, 0xb9,
	0x4b, 0x6d, 0xa6, 0x2d, 0x95, 0x48, 0x9f, 0xa5, 0x73, 0x0f, 0xa9, 0x94, 0xc8, 0x48, 0x89, 0x95,
	0x27, 0xb9, 0x18, 0xd9, 0x38, 0x64, 0xda, 0x72, 0x89, 0xd4, 0x96, 0xce, 0x3d, 0xa4, 0x52, 0x22,
	0x23, 0x25, 0x96, 0x20, 0xe1, 0x71, 0x40, 0x59, 0x8e, 0xb4, 0x92, 0x91, 0x12, 0xeb, 0x1e, 0xd2,
	0x5d, 0x09, 0x68, 0x6d, 0x17, 0x2d, 0x35, 0x00, 0x0f, 0x63, 0x76, 0x6f, 0x10, 0x62, 0x1b, 0xfb,
	0x9c, 0xa0, 0x21, 0xd3, 0x56, 0x6b, 0x4a, 0x7d, 0xdd, 0x6c, 0xcd, 0x22, 0x63, 0x2f, 0x36, 0x5b,
	0x99, 0x57, 0xa0, 0xed, 0xe7, 0xd6, 0x75, 0x6b, 0x06, 0x5a, 0xbb, 0x8b, 0xa6, 0xda, 0x06, 0x6b,
	0x1e, 0x1a, 0xf7, 0x90, 0x83, 0xb5, 0x6a, 0x4d, 0xa9, 0x6f, 0x99, 0xcd, 0x59, 0x64, 0xec, 0x7a,
	0x68, 0x7c, 0xe4, 0xe0, 0x42, 0xfb, 0x53, 0xd9, 0xbe, 0xe8, 0x40, 0xab, 0x2a, 0x25, 0xf8, 0x4b,
	0x01, 0x3b, 0x26, 0x62, 0x64, 0x70, 0x34, 0xe2, 0x6e, 0xb2, 0xef, 0x3a, 0x60, 0x7d, 0xc4, 0x70,
	0xe8, 0x23, 0x0f, 0x6b, 0x4a, 0x4d, 0xa9, 0x6f, 0x98, 0x87, 0xb3, 0xc8, 0x50, 0xe7, 0x5a, 0x01,
	0xf0, 0x4c, 0x02, 0xca, 0x1e, 0xb4, 0xd2, 0x12, 0x51, 0x18, 0x20, 0xc6, 0xce, 0x69, 0x68, 0x6b,
	0x4b, 0x59, 0xe1, 0x5c, 0xbb, 0xad, 0xb0, 0xec, 0x41, 0x2b, 0x2d, 0x81, 0x3f, 0x57, 0x81, 0x76,
	0x8c, 0xc3, 0x33, 0x32, 0xc0, 0x1f, 0xe3, 0x67, 0xd1, 0xee, 0x76, 0xbf, 0x74, 0xe4, 0xc9, 0x53,
	0x3f, 0x81, 0x2d, 0x71, 0x73, 0xfa, 0xd4, 0x9e, 0xf4, 0x18, 0xb9, 0x90, 0x6b, 0xd8, 0x32, 0x9f,
	0xcf, 0x22, 0x63, 0xd3, 0x43, 0x63, 0x93, 0xda, 0x93, 0x63, 0x72, 0x81, 0x6f, 0x22, 0x43, 0x4d,
	0xef, 0xce, 0x5c, 0x84, 0x56, 0x3e, 0xa2, 0xb6, 0xc1, 0x83, 0x10, 0x23, 0xbb, 0xc7, 0x89, 0x87,
	0xe9, 0x88, 0xc7, 0xc3, 0x27, 0x4d, 0x42, 0xef, 0x4a, 0x39, 0x6b, 0xca, 0x89, 0xd0, 0xca, 0x47,
	0x44, 0x13, 0xc3, 0x7e, 0xd6, 0xb4, 0x9c, 0x35, 0x09, 0xbd, 0xd4, 0x94, 0x13, 0xa1, 0x95, 0x8f,
	0xa8, 0x1f, 0x00, 0xf0, 0xf1, 0x98, 0xf7, 0x78, 0x48, 0xb0, 0xd8, 0xd2, 0xa2, 0x67, 0x7f, 0x16,
	0x19, 0x1b, 0x42, 0xed, 0x0a, 0xf1, 0x26, 0x32, 0x76, 0x65, 0x4b, 0x2a, 0x41, 0x2b, 0xb3, 0xc5,
	0x2c, 0xb2, 0x21, 0x99, 0x65, 0x35, 0x9b, 0x25, 0x0e, 0x2d, 0xce, 0x92, 0x13, 0xa1, 0x95, 0x8f,
	0xa4, 0xb3, 0x0c, 0x10, 0xc3, 0x4c, 0xab, 0xc6, 0xc7, 0x2b, 0x9d, 0xa5, 0x25, 0xc4, 0xe2, 0x2c,
	0xb1, 0x94, 0xcc, 0x12, 0x5f, 0xab, 0x03, 0xb0, 0x32, 0xa0, 0x21, 0xd3, 0xd6, 0x6a, 0x4a, 0x7d,
	0xf3, 0x00, 0x36, 0x6e, 0x7f, 0x5f, 0x36, 0xb2, 0xb7, 0xa2, 0xf9, 0x72, 0x16, 0x19, 0xdb, 0xe2,
	0x3f, 0x85, 0x6d, 0xf3, 0x58, 0x42, 0x8a, 0x3a, 0xb4, 0xe2, 0x72, 0x95, 0x00, 0xd0, 0x17, 0x7b,
	0xbc, 0x87, 0x46, 0xdc, 0xd5, 0xd6, 0x63, 0xd4, 0x8b, 0xbb, 0x50, 0x0b, 0xa7, 0x41, 0xae, 0xa7,
	0x3f, 0x17, 0xb3, 0xf5, 0xa4, 0x12, 0xb4, 0x32, 0xdb, 0xfc, 0x7a, 0xf5, 0x57, 0xaf, 0x7c, 0x9f,
	0xea, 0xca, 0xef, 0xa9, 0xae, 0x5c, 0x4e, 0x75, 0xe5, 0xcf, 0x54, 0x57, 0x7e, 0x5c, 0xeb, 0x95,
	0xcb, 0x6b, 0xbd, 0x72, 0x75, 0xad, 0x57, 0xbe, 0xbd, 0x75, 0x08, 0x77, 0x47, 0xfd, 0xc6, 0x80,
	0x7a, 0xcd, 0x78, 0x84, 0xd7, 0x3e, 0xe6, 0xe7, 0x34, 0x3c, 0x4d, 0x7e, 0xa1, 0x80, 0x34, 0x1d,
	0x5a, 0xfa, 0xb8, 0xf4, 0xab, 0xf1, 0x37, 0xe2, 0xf0, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99,
	0xcd, 0x3e, 0x75, 0x7d, 0x06, 0x00, 0x00,
}

func (m *CORSConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CORSConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CORSConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxAge != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.MaxAge))
		i--
		dAtA[i] = 0x30
	}
	if m.AllowCredentials {
		i--
		if m.AllowCredentials {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.ExposedHeaders) > 0 {
		for iNdEx := len(m.ExposedHeaders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ExposedHeaders[iNdEx])
			copy(dAtA[i:], m.ExposedHeaders[iNdEx])
			i = encodeVarintHttpoptions(dAtA, i, uint64(len(m.ExposedHeaders[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.AllowedHeaders) > 0 {
		for iNdEx := len(m.AllowedHeaders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedHeaders[iNdEx])
			copy(dAtA[i:], m.AllowedHeaders[iNdEx])
			i = encodeVarintHttpoptions(dAtA, i, uint64(len(m.AllowedHeaders[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.AllowedMethods) > 0 {
		for iNdEx := len(m.AllowedMethods) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedMethods[iNdEx])
			copy(dAtA[i:], m.AllowedMethods[iNdEx])
			i = encodeVarintHttpoptions(dAtA, i, uint64(len(m.AllowedMethods[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.AllowedOrigins) > 0 {
		for iNdEx := len(m.AllowedOrigins) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedOrigins[iNdEx])
			copy(dAtA[i:], m.AllowedOrigins[iNdEx])
			i = encodeVarintHttpoptions(dAtA, i, uint64(len(m.AllowedOrigins[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *BasicAuthConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BasicAuthConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BasicAuthConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintHttpoptions(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintHttpoptions(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ServiceExposeHTTPOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceExposeHTTPOptions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ServiceExposeHTTPOptions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BasicAuth != nil {
		{
			size, err := m.BasicAuth.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintHttpoptions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.Cors != nil {
		{
			size, err := m.Cors.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintHttpoptions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.NextCases) > 0 {
		for iNdEx := len(m.NextCases) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.NextCases[iNdEx])
			copy(dAtA[i:], m.NextCases[iNdEx])
			i = encodeVarintHttpoptions(dAtA, i, uint64(len(m.NextCases[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.NextTimeout != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.NextTimeout))
		i--
		dAtA[i] = 0x28
	}
	if m.NextTries != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.NextTries))
		i--
		dAtA[i] = 0x20
	}
	if m.SendTimeout != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.SendTimeout))
		i--
		dAtA[i] = 0x18
	}
	if m.ReadTimeout != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.ReadTimeout))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxBodySize != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.MaxBodySize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHttpoptions(dAtA []byte, offset int, v uint64) int {
	offset -= sovHttpoptions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CORSConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AllowedOrigins) > 0 {
		for _, s := range m.AllowedOrigins {
			l = len(s)
			n += 1 + l + sovHttpoptions(uint64(l))
		}
	}
	if len(m.AllowedMethods) > 0 {
		for _, s := range m.AllowedMethods {
			l = len(s)
			n += 1 + l + sovHttpoptions(uint64(l))
		}
	}
	if len(m.AllowedHeaders) > 0 {
		for _, s := range m.AllowedHeaders {
			l = len(s)
			n += 1 + l + sovHttpoptions(uint64(l))
		}
	}
	if len(m.ExposedHeaders) > 0 {
		for _, s := range m.ExposedHeaders {
			l = len(s)
			n += 1 + l + sovHttpoptions(uint64(l))
		}
	}
	if m.AllowCredentials {
		n += 2
	}
	if m.MaxAge != 0 {
		n += 1 + sovHttpoptions(uint64(m.MaxAge))
	}
	return n
}

func (m *BasicAuthConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovHttpoptions(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovHttpoptions(uint64(l))
	}
	return n
}

func (m *ServiceExposeHTTPOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxBodySize != 0 {
		n += 1 + sovHttpoptions(uint64(m.MaxBodySize))
	}
	if m.ReadTimeout != 0 {
		n += 1 + sovHttpoptions(uint64(m.ReadTimeout))
	}
	if m.SendTimeout != 0 {
		n += 1 + sovHttpoptions(uint64(m.SendTimeout))
	}
	if m.NextTries != 0 {
		n += 1 + sovHttpoptions(uint64(m.NextTries))
	}
	if m.NextTimeout != 0 {
		n += 1 + sovHttpoptions(uint64(m.NextTimeout))
	}
	if len(m.NextCases) > 0 {
		for _, s := range m.NextCases {
			l = len(s)
			n += 1 + l + sovHttpoptions(uint64(l))
		}
	}
	if m.Cors != nil {
		l = m.Cors.Size()
		n += 1 + l + sovHttpoptions(uint64(l))
	}
	if m.BasicAuth != nil {
		l = m.BasicAuth.Size()
		n += 1 + l + sovHttpoptions(uint64(l))
	}
	return n
}

func sovHttpoptions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHttpoptions(x uint64) (n int) {
	return sovHttpoptions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CORSConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CORSConfig{`,
		`AllowedOrigins:` + fmt.Sprintf("%v", this.AllowedOrigins) + `,`,
		`AllowedMethods:` + fmt.Sprintf("%v", this.AllowedMethods) + `,`,
		`AllowedHeaders:` + fmt.Sprintf("%v", this.AllowedHeaders) + `,`,
		`ExposedHeaders:` + fmt.Sprintf("%v", this.ExposedHeaders) + `,`,
		`AllowCredentials:` + fmt.Sprintf("%v", this.AllowCredentials) + `,`,
		`MaxAge:` + fmt.Sprintf("%v", this.MaxAge) + `,`,
		`}`,
	}, "")
	return s
}
func (this *BasicAuthConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&BasicAuthConfig{`,
		`Username:` + fmt.Sprintf("%v", this.Username) + `,`,
		`Password:` + fmt.Sprintf("%v", this.Password) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ServiceExposeHTTPOptions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ServiceExposeHTTPOptions{`,
		`MaxBodySize:` + fmt.Sprintf("%v", this.MaxBodySize) + `,`,
		`ReadTimeout:` + fmt.Sprintf("%v", this.ReadTimeout) + `,`,
		`SendTimeout:` + fmt.Sprintf("%v", this.SendTimeout) + `,`,
		`NextTries:` + fmt.Sprintf("%v", this.NextTries) + `,`,
		`NextTimeout:` + fmt.Sprintf("%v", this.NextTimeout) + `,`,
		`NextCases:` + fmt.Sprintf("%v", this.NextCases) + `,`,
		`Cors:` + strings.Replace(this.Cors.String(), "CORSConfig", "CORSConfig", 1) + `,`,
		`BasicAuth:` + strings.Replace(this.BasicAuth.String(), "BasicAuthConfig", "BasicAuthConfig", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringHttpoptions(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CORSConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHttpoptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CORSConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CORSConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedOrigins", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedOrigins = append(m.AllowedOrigins, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedMethods", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedMethods = append(m.AllowedMethods, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedHeaders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedHeaders = append(m.AllowedHeaders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExposedHeaders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExposedHeaders = append(m.ExposedHeaders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowCredentials", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowCredentials = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAge", wireType)
			}
			m.MaxAge = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAge |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHttpoptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BasicAuthConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHttpoptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BasicAuthConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BasicAuthConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHttpoptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServiceExposeHTTPOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHttpoptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceExposeHTTPOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceExposeHTTPOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBodySize", wireType)
			}
			m.MaxBodySize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBodySize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadTimeout", wireType)
			}
			m.ReadTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReadTimeout |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendTimeout", wireType)
			}
			m.SendTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SendTimeout |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextTries", wireType)
			}
			m.NextTries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextTries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextTimeout", wireType)
			}
			m.NextTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextTimeout |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextCases", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NextCases = append(m.NextCases, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Cors == nil {
				m.Cors = &CORSConfig{}
			}
			if err := m.Cors.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasicAuth", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BasicAuth == nil {
				m.BasicAuth = &BasicAuthConfig{}
			}
			if err := m.BasicAuth.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHttpoptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHttpoptions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHttpoptions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHttpoptions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHttpoptions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHttpoptions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHttpoptions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHttpoptions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHttpoptions = fmt.Errorf("proto: unexpected end of group")
)
