// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/deployment/v1beta3/group.proto

package v1beta3

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// State is an enum which refers to state of group
type Group_State int32

const (
	// Prefix should start with 0 in enum. So declaring dummy state
	GroupStateInvalid Group_State = 0
	// GroupOpen denotes state for group open
	GroupOpen Group_State = 1
	// GroupOrdered denotes state for group ordered
	GroupPaused Group_State = 2
	// GroupInsufficientFunds denotes state for group insufficient_funds
	GroupInsufficientFunds Group_State = 3
	// GroupClosed denotes state for group closed
	GroupClosed Group_State = 4
)

var Group_State_name = map[int32]string{
	0: "invalid",
	1: "open",
	2: "paused",
	3: "insufficient_funds",
	4: "closed",
}

var Group_State_value = map[string]int32{
	"invalid":            0,
	"open":               1,
	"paused":             2,
	"insufficient_funds": 3,
	"closed":             4,
}

func (x Group_State) String() string {
	return proto.EnumName(Group_State_name, int32(x))
}

func (Group_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6dcebaf6050ef7f1, []int{0, 0}
}

// Group stores group id, state and specifications of group
type Group struct {
	GroupID   GroupID     `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"id" yaml:"id"`
	State     Group_State `protobuf:"varint,2,opt,name=state,proto3,enum=akash.deployment.v1beta3.Group_State" json:"state" yaml:"state"`
	GroupSpec GroupSpec   `protobuf:"bytes,3,opt,name=group_spec,json=groupSpec,proto3" json:"spec" yaml:"spec"`
	CreatedAt int64       `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dcebaf6050ef7f1, []int{0}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Group.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return m.Size()
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupID() GroupID {
	if m != nil {
		return m.GroupID
	}
	return GroupID{}
}

func (m *Group) GetState() Group_State {
	if m != nil {
		return m.State
	}
	return GroupStateInvalid
}

func (m *Group) GetGroupSpec() GroupSpec {
	if m != nil {
		return m.GroupSpec
	}
	return GroupSpec{}
}

func (m *Group) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("akash.deployment.v1beta3.Group_State", Group_State_name, Group_State_value)
	proto.RegisterType((*Group)(nil), "akash.deployment.v1beta3.Group")
}

func init() {
	proto.RegisterFile("akash/deployment/v1beta3/group.proto", fileDescriptor_6dcebaf6050ef7f1)
}

var fileDescriptor_6dcebaf6050ef7f1 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbf, 0x8e, 0xd3, 0x30,
	0x1c, 0xc7, 0xe3, 0x36, 0xbd, 0x52, 0x97, 0x3f, 0xc5, 0xe2, 0x4f, 0xc9, 0x89, 0x38, 0x04, 0x38,
	0x75, 0x4a, 0x44, 0x6f, 0xbb, 0x09, 0x0a, 0x02, 0x75, 0x02, 0xf5, 0x24, 0x06, 0x96, 0xe2, 0x8b,
	0xdd, 0x60, 0xb5, 0x17, 0x5b, 0x8d, 0x5b, 0xe9, 0x56, 0x26, 0xd4, 0x89, 0x17, 0xa8, 0x84, 0xc4,
	0x4b, 0xf0, 0x08, 0x37, 0xde, 0xc8, 0x14, 0xa1, 0x76, 0x41, 0x1d, 0xfb, 0x04, 0xc8, 0x76, 0x10,
	0x37, 0x70, 0x77, 0x5b, 0xf2, 0xfd, 0x7e, 0x7e, 0x9f, 0xfc, 0x62, 0x19, 0x3e, 0x21, 0x63, 0x92,
	0x7f, 0x8a, 0x29, 0x93, 0x13, 0x71, 0x72, 0xcc, 0x32, 0x15, 0xcf, 0x9f, 0x1d, 0x31, 0x45, 0xf6,
	0xe3, 0x74, 0x2a, 0x66, 0x32, 0x92, 0x53, 0xa1, 0x04, 0x6a, 0x1b, 0x2a, 0xfa, 0x47, 0x45, 0x25,
	0xe5, 0xdd, 0x49, 0x45, 0x2a, 0x0c, 0x14, 0xeb, 0x27, 0xcb, 0x7b, 0x7b, 0x97, 0x5b, 0x39, 0x2d,
	0xb9, 0xce, 0xe5, 0x5c, 0x2e, 0x59, 0x62, 0xc9, 0xf0, 0xb3, 0x0b, 0x6b, 0x6f, 0x74, 0x86, 0x3e,
	0xc2, 0x6b, 0xa6, 0x1c, 0x72, 0xda, 0x06, 0x01, 0xe8, 0x34, 0xbb, 0x8f, 0xa2, 0x8b, 0xd6, 0x8b,
	0xcc, 0x48, 0xff, 0x55, 0x2f, 0x3c, 0x2d, 0xb0, 0xb3, 0x2a, 0x70, 0xbd, 0x0c, 0x36, 0x05, 0xae,
	0x70, 0xba, 0x2d, 0x70, 0xe3, 0x84, 0x1c, 0x4f, 0x0e, 0x42, 0x4e, 0xc3, 0x41, 0xdd, 0x68, 0xfb,
	0x14, 0xbd, 0x87, 0xb5, 0x5c, 0x11, 0xc5, 0xda, 0x95, 0x00, 0x74, 0x6e, 0x76, 0x9f, 0x5e, 0xa1,
	0x8f, 0x0e, 0x35, 0xdc, 0x7b, 0xb0, 0x29, 0xb0, 0x9d, 0xdb, 0x16, 0xf8, 0xba, 0xd5, 0x9a, 0xd7,
	0x70, 0x60, 0x63, 0x34, 0x84, 0xd0, 0x6e, 0xae, 0xff, 0xab, 0x5d, 0x35, 0xbb, 0x3f, 0xbe, 0x42,
	0x7e, 0x28, 0x59, 0xd2, 0xdb, 0xd5, 0xdb, 0x6f, 0x0a, 0xec, 0xea, 0xc1, 0x6d, 0x81, 0x9b, 0xa5,
	0x5d, 0xb2, 0x24, 0x1c, 0x34, 0xd2, 0xbf, 0x1c, 0x7a, 0x08, 0x61, 0x32, 0x65, 0x44, 0x31, 0x3a,
	0x24, 0xaa, 0xed, 0x06, 0xa0, 0x53, 0x1d, 0x34, 0xca, 0xe4, 0x85, 0x0a, 0x7f, 0x00, 0x58, 0x33,
	0xbb, 0xa2, 0x10, 0xd6, 0x79, 0x36, 0x27, 0x13, 0x4e, 0x5b, 0x8e, 0x77, 0x77, 0xb1, 0x0c, 0x6e,
	0xdb, 0x8f, 0xe9, 0xb2, 0x6f, 0x0b, 0x74, 0x1f, 0xba, 0x42, 0xb2, 0xac, 0x05, 0xbc, 0x1b, 0x8b,
	0x65, 0xd0, 0x30, 0xc0, 0x5b, 0xc9, 0x32, 0xb4, 0x0b, 0x77, 0x24, 0x99, 0xe5, 0x8c, 0xb6, 0x2a,
	0xde, 0xad, 0xc5, 0x32, 0x68, 0x9a, 0xea, 0x9d, 0x89, 0x50, 0x17, 0x22, 0x9e, 0xe5, 0xb3, 0xd1,
	0x88, 0x27, 0x9c, 0x65, 0x6a, 0x38, 0x9a, 0x65, 0x34, 0x6f, 0x55, 0x3d, 0x6f, 0xb1, 0x0c, 0xee,
	0xd9, 0xc3, 0x3f, 0x57, 0xbf, 0xd6, 0xad, 0x16, 0x26, 0x13, 0xa1, 0x85, 0xee, 0x39, 0xe1, 0x4b,
	0x13, 0x79, 0xee, 0x97, 0xef, 0xbe, 0x73, 0xe0, 0xfe, 0xfe, 0x86, 0x9d, 0xde, 0xf3, 0xd3, 0x95,
	0x0f, 0xce, 0x56, 0x3e, 0xf8, 0xb5, 0xf2, 0xc1, 0xd7, 0xb5, 0xef, 0x9c, 0xad, 0x7d, 0xe7, 0xe7,
	0xda, 0x77, 0x3e, 0xec, 0xc9, 0x71, 0x1a, 0x91, 0xb1, 0x8a, 0x28, 0x9b, 0xc7, 0xa9, 0x88, 0x33,
	0x41, 0xd9, 0x7f, 0xae, 0xd5, 0xd1, 0x8e, 0xb9, 0x4d, 0xfb, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xbe, 0x40, 0x58, 0xd0, 0xf7, 0x02, 0x00, 0x00,
}

func (m *Group) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Group) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Group) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintGroup(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.GroupSpec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGroup(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.State != 0 {
		i = encodeVarintGroup(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.GroupID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGroup(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGroup(dAtA []byte, offset int, v uint64) int {
	offset -= sovGroup(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Group) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.GroupID.Size()
	n += 1 + l + sovGroup(uint64(l))
	if m.State != 0 {
		n += 1 + sovGroup(uint64(m.State))
	}
	l = m.GroupSpec.Size()
	n += 1 + l + sovGroup(uint64(l))
	if m.CreatedAt != 0 {
		n += 1 + sovGroup(uint64(m.CreatedAt))
	}
	return n
}

func sovGroup(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGroup(x uint64) (n int) {
	return sovGroup(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Group) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGroup
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Group: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Group: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGroup
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGroup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GroupID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= Group_State(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupSpec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGroup
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGroup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GroupSpec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGroup(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGroup
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGroup(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGroup
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGroup
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGroup
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGroup
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGroup
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGroup
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGroup        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGroup          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGroup = fmt.Errorf("proto: unexpected end of group")
)
