// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	authz "github.com/cosmos/cosmos-sdk/x/authz"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"

	certv1beta3 "github.com/akash-network/akash-api/go/node/cert/v1beta3"

	client "github.com/cosmos/cosmos-sdk/client"

	context "context"

	deploymentv1beta3 "github.com/akash-network/akash-api/go/node/deployment/v1beta3"

	distributiontypes "github.com/cosmos/cosmos-sdk/x/distribution/types"

	evidencetypes "github.com/cosmos/cosmos-sdk/x/evidence/types"

	feegrant "github.com/cosmos/cosmos-sdk/x/feegrant"

	govtypes "github.com/cosmos/cosmos-sdk/x/gov/types"

	grpc "google.golang.org/grpc"

	minttypes "github.com/cosmos/cosmos-sdk/x/mint/types"

	mock "github.com/stretchr/testify/mock"

	proposal "github.com/cosmos/cosmos-sdk/x/params/types/proposal"

	providerv1beta3 "github.com/akash-network/akash-api/go/node/provider/v1beta3"

	slashingtypes "github.com/cosmos/cosmos-sdk/x/slashing/types"

	stakingtypes "github.com/cosmos/cosmos-sdk/x/staking/types"

	types "github.com/cosmos/cosmos-sdk/x/auth/types"

	upgradetypes "github.com/cosmos/cosmos-sdk/x/upgrade/types"

	v1beta3 "github.com/akash-network/akash-api/go/node/audit/v1beta3"

	v1beta4 "github.com/akash-network/akash-api/go/node/market/v1beta4"
)

// QueryClient is an autogenerated mock type for the QueryClient type
type QueryClient struct {
	mock.Mock
}

type QueryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryClient) EXPECT() *QueryClient_Expecter {
	return &QueryClient_Expecter{mock: &_m.Mock}
}

// AllProvidersAttributes provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) AllProvidersAttributes(ctx context.Context, in *v1beta3.QueryAllProvidersAttributesRequest, opts ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AllProvidersAttributes")
	}

	var r0 *v1beta3.QueryProvidersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta3.QueryAllProvidersAttributesRequest, ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta3.QueryAllProvidersAttributesRequest, ...grpc.CallOption) *v1beta3.QueryProvidersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta3.QueryProvidersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta3.QueryAllProvidersAttributesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_AllProvidersAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllProvidersAttributes'
type QueryClient_AllProvidersAttributes_Call struct {
	*mock.Call
}

// AllProvidersAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta3.QueryAllProvidersAttributesRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) AllProvidersAttributes(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_AllProvidersAttributes_Call {
	return &QueryClient_AllProvidersAttributes_Call{Call: _e.mock.On("AllProvidersAttributes",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_AllProvidersAttributes_Call) Run(run func(ctx context.Context, in *v1beta3.QueryAllProvidersAttributesRequest, opts ...grpc.CallOption)) *QueryClient_AllProvidersAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta3.QueryAllProvidersAttributesRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_AllProvidersAttributes_Call) Return(_a0 *v1beta3.QueryProvidersResponse, _a1 error) *QueryClient_AllProvidersAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_AllProvidersAttributes_Call) RunAndReturn(run func(context.Context, *v1beta3.QueryAllProvidersAttributesRequest, ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error)) *QueryClient_AllProvidersAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// AuditorAttributes provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) AuditorAttributes(ctx context.Context, in *v1beta3.QueryAuditorAttributesRequest, opts ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AuditorAttributes")
	}

	var r0 *v1beta3.QueryProvidersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta3.QueryAuditorAttributesRequest, ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta3.QueryAuditorAttributesRequest, ...grpc.CallOption) *v1beta3.QueryProvidersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta3.QueryProvidersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta3.QueryAuditorAttributesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_AuditorAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuditorAttributes'
type QueryClient_AuditorAttributes_Call struct {
	*mock.Call
}

// AuditorAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta3.QueryAuditorAttributesRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) AuditorAttributes(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_AuditorAttributes_Call {
	return &QueryClient_AuditorAttributes_Call{Call: _e.mock.On("AuditorAttributes",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_AuditorAttributes_Call) Run(run func(ctx context.Context, in *v1beta3.QueryAuditorAttributesRequest, opts ...grpc.CallOption)) *QueryClient_AuditorAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta3.QueryAuditorAttributesRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_AuditorAttributes_Call) Return(_a0 *v1beta3.QueryProvidersResponse, _a1 error) *QueryClient_AuditorAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_AuditorAttributes_Call) RunAndReturn(run func(context.Context, *v1beta3.QueryAuditorAttributesRequest, ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error)) *QueryClient_AuditorAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// Auth provides a mock function with given fields:
func (_m *QueryClient) Auth() types.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 types.QueryClient
	if rf, ok := ret.Get(0).(func() types.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.QueryClient)
		}
	}

	return r0
}

// QueryClient_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type QueryClient_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Auth() *QueryClient_Auth_Call {
	return &QueryClient_Auth_Call{Call: _e.mock.On("Auth")}
}

func (_c *QueryClient_Auth_Call) Run(run func()) *QueryClient_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Auth_Call) Return(_a0 types.QueryClient) *QueryClient_Auth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Auth_Call) RunAndReturn(run func() types.QueryClient) *QueryClient_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// Authz provides a mock function with given fields:
func (_m *QueryClient) Authz() authz.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Authz")
	}

	var r0 authz.QueryClient
	if rf, ok := ret.Get(0).(func() authz.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authz.QueryClient)
		}
	}

	return r0
}

// QueryClient_Authz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authz'
type QueryClient_Authz_Call struct {
	*mock.Call
}

// Authz is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Authz() *QueryClient_Authz_Call {
	return &QueryClient_Authz_Call{Call: _e.mock.On("Authz")}
}

func (_c *QueryClient_Authz_Call) Run(run func()) *QueryClient_Authz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Authz_Call) Return(_a0 authz.QueryClient) *QueryClient_Authz_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Authz_Call) RunAndReturn(run func() authz.QueryClient) *QueryClient_Authz_Call {
	_c.Call.Return(run)
	return _c
}

// Bank provides a mock function with given fields:
func (_m *QueryClient) Bank() banktypes.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bank")
	}

	var r0 banktypes.QueryClient
	if rf, ok := ret.Get(0).(func() banktypes.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(banktypes.QueryClient)
		}
	}

	return r0
}

// QueryClient_Bank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bank'
type QueryClient_Bank_Call struct {
	*mock.Call
}

// Bank is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Bank() *QueryClient_Bank_Call {
	return &QueryClient_Bank_Call{Call: _e.mock.On("Bank")}
}

func (_c *QueryClient_Bank_Call) Run(run func()) *QueryClient_Bank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Bank_Call) Return(_a0 banktypes.QueryClient) *QueryClient_Bank_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Bank_Call) RunAndReturn(run func() banktypes.QueryClient) *QueryClient_Bank_Call {
	_c.Call.Return(run)
	return _c
}

// Bid provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Bid(ctx context.Context, in *v1beta4.QueryBidRequest, opts ...grpc.CallOption) (*v1beta4.QueryBidResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Bid")
	}

	var r0 *v1beta4.QueryBidResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryBidRequest, ...grpc.CallOption) (*v1beta4.QueryBidResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryBidRequest, ...grpc.CallOption) *v1beta4.QueryBidResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta4.QueryBidResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta4.QueryBidRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Bid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bid'
type QueryClient_Bid_Call struct {
	*mock.Call
}

// Bid is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta4.QueryBidRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Bid(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Bid_Call {
	return &QueryClient_Bid_Call{Call: _e.mock.On("Bid",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Bid_Call) Run(run func(ctx context.Context, in *v1beta4.QueryBidRequest, opts ...grpc.CallOption)) *QueryClient_Bid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta4.QueryBidRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Bid_Call) Return(_a0 *v1beta4.QueryBidResponse, _a1 error) *QueryClient_Bid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Bid_Call) RunAndReturn(run func(context.Context, *v1beta4.QueryBidRequest, ...grpc.CallOption) (*v1beta4.QueryBidResponse, error)) *QueryClient_Bid_Call {
	_c.Call.Return(run)
	return _c
}

// Bids provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Bids(ctx context.Context, in *v1beta4.QueryBidsRequest, opts ...grpc.CallOption) (*v1beta4.QueryBidsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Bids")
	}

	var r0 *v1beta4.QueryBidsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryBidsRequest, ...grpc.CallOption) (*v1beta4.QueryBidsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryBidsRequest, ...grpc.CallOption) *v1beta4.QueryBidsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta4.QueryBidsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta4.QueryBidsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Bids_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bids'
type QueryClient_Bids_Call struct {
	*mock.Call
}

// Bids is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta4.QueryBidsRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Bids(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Bids_Call {
	return &QueryClient_Bids_Call{Call: _e.mock.On("Bids",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Bids_Call) Run(run func(ctx context.Context, in *v1beta4.QueryBidsRequest, opts ...grpc.CallOption)) *QueryClient_Bids_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta4.QueryBidsRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Bids_Call) Return(_a0 *v1beta4.QueryBidsResponse, _a1 error) *QueryClient_Bids_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Bids_Call) RunAndReturn(run func(context.Context, *v1beta4.QueryBidsRequest, ...grpc.CallOption) (*v1beta4.QueryBidsResponse, error)) *QueryClient_Bids_Call {
	_c.Call.Return(run)
	return _c
}

// Certificates provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Certificates(ctx context.Context, in *certv1beta3.QueryCertificatesRequest, opts ...grpc.CallOption) (*certv1beta3.QueryCertificatesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Certificates")
	}

	var r0 *certv1beta3.QueryCertificatesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *certv1beta3.QueryCertificatesRequest, ...grpc.CallOption) (*certv1beta3.QueryCertificatesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *certv1beta3.QueryCertificatesRequest, ...grpc.CallOption) *certv1beta3.QueryCertificatesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certv1beta3.QueryCertificatesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *certv1beta3.QueryCertificatesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Certificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Certificates'
type QueryClient_Certificates_Call struct {
	*mock.Call
}

// Certificates is a helper method to define mock.On call
//   - ctx context.Context
//   - in *certv1beta3.QueryCertificatesRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Certificates(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Certificates_Call {
	return &QueryClient_Certificates_Call{Call: _e.mock.On("Certificates",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Certificates_Call) Run(run func(ctx context.Context, in *certv1beta3.QueryCertificatesRequest, opts ...grpc.CallOption)) *QueryClient_Certificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*certv1beta3.QueryCertificatesRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Certificates_Call) Return(_a0 *certv1beta3.QueryCertificatesResponse, _a1 error) *QueryClient_Certificates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Certificates_Call) RunAndReturn(run func(context.Context, *certv1beta3.QueryCertificatesRequest, ...grpc.CallOption) (*certv1beta3.QueryCertificatesResponse, error)) *QueryClient_Certificates_Call {
	_c.Call.Return(run)
	return _c
}

// ClientContext provides a mock function with given fields:
func (_m *QueryClient) ClientContext() client.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClientContext")
	}

	var r0 client.Context
	if rf, ok := ret.Get(0).(func() client.Context); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(client.Context)
	}

	return r0
}

// QueryClient_ClientContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientContext'
type QueryClient_ClientContext_Call struct {
	*mock.Call
}

// ClientContext is a helper method to define mock.On call
func (_e *QueryClient_Expecter) ClientContext() *QueryClient_ClientContext_Call {
	return &QueryClient_ClientContext_Call{Call: _e.mock.On("ClientContext")}
}

func (_c *QueryClient_ClientContext_Call) Run(run func()) *QueryClient_ClientContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_ClientContext_Call) Return(_a0 client.Context) *QueryClient_ClientContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_ClientContext_Call) RunAndReturn(run func() client.Context) *QueryClient_ClientContext_Call {
	_c.Call.Return(run)
	return _c
}

// Deployment provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Deployment(ctx context.Context, in *deploymentv1beta3.QueryDeploymentRequest, opts ...grpc.CallOption) (*deploymentv1beta3.QueryDeploymentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Deployment")
	}

	var r0 *deploymentv1beta3.QueryDeploymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *deploymentv1beta3.QueryDeploymentRequest, ...grpc.CallOption) (*deploymentv1beta3.QueryDeploymentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *deploymentv1beta3.QueryDeploymentRequest, ...grpc.CallOption) *deploymentv1beta3.QueryDeploymentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deploymentv1beta3.QueryDeploymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *deploymentv1beta3.QueryDeploymentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Deployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deployment'
type QueryClient_Deployment_Call struct {
	*mock.Call
}

// Deployment is a helper method to define mock.On call
//   - ctx context.Context
//   - in *deploymentv1beta3.QueryDeploymentRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Deployment(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Deployment_Call {
	return &QueryClient_Deployment_Call{Call: _e.mock.On("Deployment",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Deployment_Call) Run(run func(ctx context.Context, in *deploymentv1beta3.QueryDeploymentRequest, opts ...grpc.CallOption)) *QueryClient_Deployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*deploymentv1beta3.QueryDeploymentRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Deployment_Call) Return(_a0 *deploymentv1beta3.QueryDeploymentResponse, _a1 error) *QueryClient_Deployment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Deployment_Call) RunAndReturn(run func(context.Context, *deploymentv1beta3.QueryDeploymentRequest, ...grpc.CallOption) (*deploymentv1beta3.QueryDeploymentResponse, error)) *QueryClient_Deployment_Call {
	_c.Call.Return(run)
	return _c
}

// Deployments provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Deployments(ctx context.Context, in *deploymentv1beta3.QueryDeploymentsRequest, opts ...grpc.CallOption) (*deploymentv1beta3.QueryDeploymentsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Deployments")
	}

	var r0 *deploymentv1beta3.QueryDeploymentsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *deploymentv1beta3.QueryDeploymentsRequest, ...grpc.CallOption) (*deploymentv1beta3.QueryDeploymentsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *deploymentv1beta3.QueryDeploymentsRequest, ...grpc.CallOption) *deploymentv1beta3.QueryDeploymentsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deploymentv1beta3.QueryDeploymentsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *deploymentv1beta3.QueryDeploymentsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Deployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deployments'
type QueryClient_Deployments_Call struct {
	*mock.Call
}

// Deployments is a helper method to define mock.On call
//   - ctx context.Context
//   - in *deploymentv1beta3.QueryDeploymentsRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Deployments(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Deployments_Call {
	return &QueryClient_Deployments_Call{Call: _e.mock.On("Deployments",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Deployments_Call) Run(run func(ctx context.Context, in *deploymentv1beta3.QueryDeploymentsRequest, opts ...grpc.CallOption)) *QueryClient_Deployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*deploymentv1beta3.QueryDeploymentsRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Deployments_Call) Return(_a0 *deploymentv1beta3.QueryDeploymentsResponse, _a1 error) *QueryClient_Deployments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Deployments_Call) RunAndReturn(run func(context.Context, *deploymentv1beta3.QueryDeploymentsRequest, ...grpc.CallOption) (*deploymentv1beta3.QueryDeploymentsResponse, error)) *QueryClient_Deployments_Call {
	_c.Call.Return(run)
	return _c
}

// Distribution provides a mock function with given fields:
func (_m *QueryClient) Distribution() distributiontypes.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Distribution")
	}

	var r0 distributiontypes.QueryClient
	if rf, ok := ret.Get(0).(func() distributiontypes.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(distributiontypes.QueryClient)
		}
	}

	return r0
}

// QueryClient_Distribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Distribution'
type QueryClient_Distribution_Call struct {
	*mock.Call
}

// Distribution is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Distribution() *QueryClient_Distribution_Call {
	return &QueryClient_Distribution_Call{Call: _e.mock.On("Distribution")}
}

func (_c *QueryClient_Distribution_Call) Run(run func()) *QueryClient_Distribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Distribution_Call) Return(_a0 distributiontypes.QueryClient) *QueryClient_Distribution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Distribution_Call) RunAndReturn(run func() distributiontypes.QueryClient) *QueryClient_Distribution_Call {
	_c.Call.Return(run)
	return _c
}

// Evidence provides a mock function with given fields:
func (_m *QueryClient) Evidence() evidencetypes.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Evidence")
	}

	var r0 evidencetypes.QueryClient
	if rf, ok := ret.Get(0).(func() evidencetypes.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(evidencetypes.QueryClient)
		}
	}

	return r0
}

// QueryClient_Evidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evidence'
type QueryClient_Evidence_Call struct {
	*mock.Call
}

// Evidence is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Evidence() *QueryClient_Evidence_Call {
	return &QueryClient_Evidence_Call{Call: _e.mock.On("Evidence")}
}

func (_c *QueryClient_Evidence_Call) Run(run func()) *QueryClient_Evidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Evidence_Call) Return(_a0 evidencetypes.QueryClient) *QueryClient_Evidence_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Evidence_Call) RunAndReturn(run func() evidencetypes.QueryClient) *QueryClient_Evidence_Call {
	_c.Call.Return(run)
	return _c
}

// Feegrant provides a mock function with given fields:
func (_m *QueryClient) Feegrant() feegrant.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Feegrant")
	}

	var r0 feegrant.QueryClient
	if rf, ok := ret.Get(0).(func() feegrant.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(feegrant.QueryClient)
		}
	}

	return r0
}

// QueryClient_Feegrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Feegrant'
type QueryClient_Feegrant_Call struct {
	*mock.Call
}

// Feegrant is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Feegrant() *QueryClient_Feegrant_Call {
	return &QueryClient_Feegrant_Call{Call: _e.mock.On("Feegrant")}
}

func (_c *QueryClient_Feegrant_Call) Run(run func()) *QueryClient_Feegrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Feegrant_Call) Return(_a0 feegrant.QueryClient) *QueryClient_Feegrant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Feegrant_Call) RunAndReturn(run func() feegrant.QueryClient) *QueryClient_Feegrant_Call {
	_c.Call.Return(run)
	return _c
}

// Gov provides a mock function with given fields:
func (_m *QueryClient) Gov() govtypes.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Gov")
	}

	var r0 govtypes.QueryClient
	if rf, ok := ret.Get(0).(func() govtypes.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(govtypes.QueryClient)
		}
	}

	return r0
}

// QueryClient_Gov_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Gov'
type QueryClient_Gov_Call struct {
	*mock.Call
}

// Gov is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Gov() *QueryClient_Gov_Call {
	return &QueryClient_Gov_Call{Call: _e.mock.On("Gov")}
}

func (_c *QueryClient_Gov_Call) Run(run func()) *QueryClient_Gov_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Gov_Call) Return(_a0 govtypes.QueryClient) *QueryClient_Gov_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Gov_Call) RunAndReturn(run func() govtypes.QueryClient) *QueryClient_Gov_Call {
	_c.Call.Return(run)
	return _c
}

// Group provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Group(ctx context.Context, in *deploymentv1beta3.QueryGroupRequest, opts ...grpc.CallOption) (*deploymentv1beta3.QueryGroupResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 *deploymentv1beta3.QueryGroupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *deploymentv1beta3.QueryGroupRequest, ...grpc.CallOption) (*deploymentv1beta3.QueryGroupResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *deploymentv1beta3.QueryGroupRequest, ...grpc.CallOption) *deploymentv1beta3.QueryGroupResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deploymentv1beta3.QueryGroupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *deploymentv1beta3.QueryGroupRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type QueryClient_Group_Call struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
//   - ctx context.Context
//   - in *deploymentv1beta3.QueryGroupRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Group(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Group_Call {
	return &QueryClient_Group_Call{Call: _e.mock.On("Group",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Group_Call) Run(run func(ctx context.Context, in *deploymentv1beta3.QueryGroupRequest, opts ...grpc.CallOption)) *QueryClient_Group_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*deploymentv1beta3.QueryGroupRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Group_Call) Return(_a0 *deploymentv1beta3.QueryGroupResponse, _a1 error) *QueryClient_Group_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Group_Call) RunAndReturn(run func(context.Context, *deploymentv1beta3.QueryGroupRequest, ...grpc.CallOption) (*deploymentv1beta3.QueryGroupResponse, error)) *QueryClient_Group_Call {
	_c.Call.Return(run)
	return _c
}

// Lease provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Lease(ctx context.Context, in *v1beta4.QueryLeaseRequest, opts ...grpc.CallOption) (*v1beta4.QueryLeaseResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Lease")
	}

	var r0 *v1beta4.QueryLeaseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryLeaseRequest, ...grpc.CallOption) (*v1beta4.QueryLeaseResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryLeaseRequest, ...grpc.CallOption) *v1beta4.QueryLeaseResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta4.QueryLeaseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta4.QueryLeaseRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Lease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lease'
type QueryClient_Lease_Call struct {
	*mock.Call
}

// Lease is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta4.QueryLeaseRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Lease(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Lease_Call {
	return &QueryClient_Lease_Call{Call: _e.mock.On("Lease",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Lease_Call) Run(run func(ctx context.Context, in *v1beta4.QueryLeaseRequest, opts ...grpc.CallOption)) *QueryClient_Lease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta4.QueryLeaseRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Lease_Call) Return(_a0 *v1beta4.QueryLeaseResponse, _a1 error) *QueryClient_Lease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Lease_Call) RunAndReturn(run func(context.Context, *v1beta4.QueryLeaseRequest, ...grpc.CallOption) (*v1beta4.QueryLeaseResponse, error)) *QueryClient_Lease_Call {
	_c.Call.Return(run)
	return _c
}

// Leases provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Leases(ctx context.Context, in *v1beta4.QueryLeasesRequest, opts ...grpc.CallOption) (*v1beta4.QueryLeasesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Leases")
	}

	var r0 *v1beta4.QueryLeasesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryLeasesRequest, ...grpc.CallOption) (*v1beta4.QueryLeasesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryLeasesRequest, ...grpc.CallOption) *v1beta4.QueryLeasesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta4.QueryLeasesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta4.QueryLeasesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Leases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leases'
type QueryClient_Leases_Call struct {
	*mock.Call
}

// Leases is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta4.QueryLeasesRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Leases(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Leases_Call {
	return &QueryClient_Leases_Call{Call: _e.mock.On("Leases",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Leases_Call) Run(run func(ctx context.Context, in *v1beta4.QueryLeasesRequest, opts ...grpc.CallOption)) *QueryClient_Leases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta4.QueryLeasesRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Leases_Call) Return(_a0 *v1beta4.QueryLeasesResponse, _a1 error) *QueryClient_Leases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Leases_Call) RunAndReturn(run func(context.Context, *v1beta4.QueryLeasesRequest, ...grpc.CallOption) (*v1beta4.QueryLeasesResponse, error)) *QueryClient_Leases_Call {
	_c.Call.Return(run)
	return _c
}

// Mint provides a mock function with given fields:
func (_m *QueryClient) Mint() minttypes.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mint")
	}

	var r0 minttypes.QueryClient
	if rf, ok := ret.Get(0).(func() minttypes.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(minttypes.QueryClient)
		}
	}

	return r0
}

// QueryClient_Mint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mint'
type QueryClient_Mint_Call struct {
	*mock.Call
}

// Mint is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Mint() *QueryClient_Mint_Call {
	return &QueryClient_Mint_Call{Call: _e.mock.On("Mint")}
}

func (_c *QueryClient_Mint_Call) Run(run func()) *QueryClient_Mint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Mint_Call) Return(_a0 minttypes.QueryClient) *QueryClient_Mint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Mint_Call) RunAndReturn(run func() minttypes.QueryClient) *QueryClient_Mint_Call {
	_c.Call.Return(run)
	return _c
}

// Order provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Order(ctx context.Context, in *v1beta4.QueryOrderRequest, opts ...grpc.CallOption) (*v1beta4.QueryOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Order")
	}

	var r0 *v1beta4.QueryOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryOrderRequest, ...grpc.CallOption) (*v1beta4.QueryOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryOrderRequest, ...grpc.CallOption) *v1beta4.QueryOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta4.QueryOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta4.QueryOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Order_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Order'
type QueryClient_Order_Call struct {
	*mock.Call
}

// Order is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta4.QueryOrderRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Order(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Order_Call {
	return &QueryClient_Order_Call{Call: _e.mock.On("Order",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Order_Call) Run(run func(ctx context.Context, in *v1beta4.QueryOrderRequest, opts ...grpc.CallOption)) *QueryClient_Order_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta4.QueryOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Order_Call) Return(_a0 *v1beta4.QueryOrderResponse, _a1 error) *QueryClient_Order_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Order_Call) RunAndReturn(run func(context.Context, *v1beta4.QueryOrderRequest, ...grpc.CallOption) (*v1beta4.QueryOrderResponse, error)) *QueryClient_Order_Call {
	_c.Call.Return(run)
	return _c
}

// Orders provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Orders(ctx context.Context, in *v1beta4.QueryOrdersRequest, opts ...grpc.CallOption) (*v1beta4.QueryOrdersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Orders")
	}

	var r0 *v1beta4.QueryOrdersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryOrdersRequest, ...grpc.CallOption) (*v1beta4.QueryOrdersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta4.QueryOrdersRequest, ...grpc.CallOption) *v1beta4.QueryOrdersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta4.QueryOrdersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta4.QueryOrdersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Orders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Orders'
type QueryClient_Orders_Call struct {
	*mock.Call
}

// Orders is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta4.QueryOrdersRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Orders(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Orders_Call {
	return &QueryClient_Orders_Call{Call: _e.mock.On("Orders",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Orders_Call) Run(run func(ctx context.Context, in *v1beta4.QueryOrdersRequest, opts ...grpc.CallOption)) *QueryClient_Orders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta4.QueryOrdersRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Orders_Call) Return(_a0 *v1beta4.QueryOrdersResponse, _a1 error) *QueryClient_Orders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Orders_Call) RunAndReturn(run func(context.Context, *v1beta4.QueryOrdersRequest, ...grpc.CallOption) (*v1beta4.QueryOrdersResponse, error)) *QueryClient_Orders_Call {
	_c.Call.Return(run)
	return _c
}

// Params provides a mock function with given fields:
func (_m *QueryClient) Params() proposal.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Params")
	}

	var r0 proposal.QueryClient
	if rf, ok := ret.Get(0).(func() proposal.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proposal.QueryClient)
		}
	}

	return r0
}

// QueryClient_Params_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Params'
type QueryClient_Params_Call struct {
	*mock.Call
}

// Params is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Params() *QueryClient_Params_Call {
	return &QueryClient_Params_Call{Call: _e.mock.On("Params")}
}

func (_c *QueryClient_Params_Call) Run(run func()) *QueryClient_Params_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Params_Call) Return(_a0 proposal.QueryClient) *QueryClient_Params_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Params_Call) RunAndReturn(run func() proposal.QueryClient) *QueryClient_Params_Call {
	_c.Call.Return(run)
	return _c
}

// Provider provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Provider(ctx context.Context, in *providerv1beta3.QueryProviderRequest, opts ...grpc.CallOption) (*providerv1beta3.QueryProviderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Provider")
	}

	var r0 *providerv1beta3.QueryProviderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *providerv1beta3.QueryProviderRequest, ...grpc.CallOption) (*providerv1beta3.QueryProviderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *providerv1beta3.QueryProviderRequest, ...grpc.CallOption) *providerv1beta3.QueryProviderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providerv1beta3.QueryProviderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *providerv1beta3.QueryProviderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Provider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provider'
type QueryClient_Provider_Call struct {
	*mock.Call
}

// Provider is a helper method to define mock.On call
//   - ctx context.Context
//   - in *providerv1beta3.QueryProviderRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Provider(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Provider_Call {
	return &QueryClient_Provider_Call{Call: _e.mock.On("Provider",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Provider_Call) Run(run func(ctx context.Context, in *providerv1beta3.QueryProviderRequest, opts ...grpc.CallOption)) *QueryClient_Provider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*providerv1beta3.QueryProviderRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Provider_Call) Return(_a0 *providerv1beta3.QueryProviderResponse, _a1 error) *QueryClient_Provider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Provider_Call) RunAndReturn(run func(context.Context, *providerv1beta3.QueryProviderRequest, ...grpc.CallOption) (*providerv1beta3.QueryProviderResponse, error)) *QueryClient_Provider_Call {
	_c.Call.Return(run)
	return _c
}

// ProviderAttributes provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) ProviderAttributes(ctx context.Context, in *v1beta3.QueryProviderAttributesRequest, opts ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ProviderAttributes")
	}

	var r0 *v1beta3.QueryProvidersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta3.QueryProviderAttributesRequest, ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta3.QueryProviderAttributesRequest, ...grpc.CallOption) *v1beta3.QueryProvidersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta3.QueryProvidersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta3.QueryProviderAttributesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_ProviderAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProviderAttributes'
type QueryClient_ProviderAttributes_Call struct {
	*mock.Call
}

// ProviderAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta3.QueryProviderAttributesRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) ProviderAttributes(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_ProviderAttributes_Call {
	return &QueryClient_ProviderAttributes_Call{Call: _e.mock.On("ProviderAttributes",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_ProviderAttributes_Call) Run(run func(ctx context.Context, in *v1beta3.QueryProviderAttributesRequest, opts ...grpc.CallOption)) *QueryClient_ProviderAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta3.QueryProviderAttributesRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_ProviderAttributes_Call) Return(_a0 *v1beta3.QueryProvidersResponse, _a1 error) *QueryClient_ProviderAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_ProviderAttributes_Call) RunAndReturn(run func(context.Context, *v1beta3.QueryProviderAttributesRequest, ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error)) *QueryClient_ProviderAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// ProviderAuditorAttributes provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) ProviderAuditorAttributes(ctx context.Context, in *v1beta3.QueryProviderAuditorRequest, opts ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ProviderAuditorAttributes")
	}

	var r0 *v1beta3.QueryProvidersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta3.QueryProviderAuditorRequest, ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta3.QueryProviderAuditorRequest, ...grpc.CallOption) *v1beta3.QueryProvidersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta3.QueryProvidersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta3.QueryProviderAuditorRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_ProviderAuditorAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProviderAuditorAttributes'
type QueryClient_ProviderAuditorAttributes_Call struct {
	*mock.Call
}

// ProviderAuditorAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1beta3.QueryProviderAuditorRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) ProviderAuditorAttributes(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_ProviderAuditorAttributes_Call {
	return &QueryClient_ProviderAuditorAttributes_Call{Call: _e.mock.On("ProviderAuditorAttributes",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_ProviderAuditorAttributes_Call) Run(run func(ctx context.Context, in *v1beta3.QueryProviderAuditorRequest, opts ...grpc.CallOption)) *QueryClient_ProviderAuditorAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1beta3.QueryProviderAuditorRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_ProviderAuditorAttributes_Call) Return(_a0 *v1beta3.QueryProvidersResponse, _a1 error) *QueryClient_ProviderAuditorAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_ProviderAuditorAttributes_Call) RunAndReturn(run func(context.Context, *v1beta3.QueryProviderAuditorRequest, ...grpc.CallOption) (*v1beta3.QueryProvidersResponse, error)) *QueryClient_ProviderAuditorAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// Providers provides a mock function with given fields: ctx, in, opts
func (_m *QueryClient) Providers(ctx context.Context, in *providerv1beta3.QueryProvidersRequest, opts ...grpc.CallOption) (*providerv1beta3.QueryProvidersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Providers")
	}

	var r0 *providerv1beta3.QueryProvidersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *providerv1beta3.QueryProvidersRequest, ...grpc.CallOption) (*providerv1beta3.QueryProvidersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *providerv1beta3.QueryProvidersRequest, ...grpc.CallOption) *providerv1beta3.QueryProvidersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providerv1beta3.QueryProvidersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *providerv1beta3.QueryProvidersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryClient_Providers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Providers'
type QueryClient_Providers_Call struct {
	*mock.Call
}

// Providers is a helper method to define mock.On call
//   - ctx context.Context
//   - in *providerv1beta3.QueryProvidersRequest
//   - opts ...grpc.CallOption
func (_e *QueryClient_Expecter) Providers(ctx interface{}, in interface{}, opts ...interface{}) *QueryClient_Providers_Call {
	return &QueryClient_Providers_Call{Call: _e.mock.On("Providers",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *QueryClient_Providers_Call) Run(run func(ctx context.Context, in *providerv1beta3.QueryProvidersRequest, opts ...grpc.CallOption)) *QueryClient_Providers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*providerv1beta3.QueryProvidersRequest), variadicArgs...)
	})
	return _c
}

func (_c *QueryClient_Providers_Call) Return(_a0 *providerv1beta3.QueryProvidersResponse, _a1 error) *QueryClient_Providers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryClient_Providers_Call) RunAndReturn(run func(context.Context, *providerv1beta3.QueryProvidersRequest, ...grpc.CallOption) (*providerv1beta3.QueryProvidersResponse, error)) *QueryClient_Providers_Call {
	_c.Call.Return(run)
	return _c
}

// Slashing provides a mock function with given fields:
func (_m *QueryClient) Slashing() slashingtypes.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Slashing")
	}

	var r0 slashingtypes.QueryClient
	if rf, ok := ret.Get(0).(func() slashingtypes.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slashingtypes.QueryClient)
		}
	}

	return r0
}

// QueryClient_Slashing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Slashing'
type QueryClient_Slashing_Call struct {
	*mock.Call
}

// Slashing is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Slashing() *QueryClient_Slashing_Call {
	return &QueryClient_Slashing_Call{Call: _e.mock.On("Slashing")}
}

func (_c *QueryClient_Slashing_Call) Run(run func()) *QueryClient_Slashing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Slashing_Call) Return(_a0 slashingtypes.QueryClient) *QueryClient_Slashing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Slashing_Call) RunAndReturn(run func() slashingtypes.QueryClient) *QueryClient_Slashing_Call {
	_c.Call.Return(run)
	return _c
}

// Staking provides a mock function with given fields:
func (_m *QueryClient) Staking() stakingtypes.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Staking")
	}

	var r0 stakingtypes.QueryClient
	if rf, ok := ret.Get(0).(func() stakingtypes.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stakingtypes.QueryClient)
		}
	}

	return r0
}

// QueryClient_Staking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Staking'
type QueryClient_Staking_Call struct {
	*mock.Call
}

// Staking is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Staking() *QueryClient_Staking_Call {
	return &QueryClient_Staking_Call{Call: _e.mock.On("Staking")}
}

func (_c *QueryClient_Staking_Call) Run(run func()) *QueryClient_Staking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Staking_Call) Return(_a0 stakingtypes.QueryClient) *QueryClient_Staking_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Staking_Call) RunAndReturn(run func() stakingtypes.QueryClient) *QueryClient_Staking_Call {
	_c.Call.Return(run)
	return _c
}

// Upgrade provides a mock function with given fields:
func (_m *QueryClient) Upgrade() upgradetypes.QueryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Upgrade")
	}

	var r0 upgradetypes.QueryClient
	if rf, ok := ret.Get(0).(func() upgradetypes.QueryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(upgradetypes.QueryClient)
		}
	}

	return r0
}

// QueryClient_Upgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upgrade'
type QueryClient_Upgrade_Call struct {
	*mock.Call
}

// Upgrade is a helper method to define mock.On call
func (_e *QueryClient_Expecter) Upgrade() *QueryClient_Upgrade_Call {
	return &QueryClient_Upgrade_Call{Call: _e.mock.On("Upgrade")}
}

func (_c *QueryClient_Upgrade_Call) Run(run func()) *QueryClient_Upgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryClient_Upgrade_Call) Return(_a0 upgradetypes.QueryClient) *QueryClient_Upgrade_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryClient_Upgrade_Call) RunAndReturn(run func() upgradetypes.QueryClient) *QueryClient_Upgrade_Call {
	_c.Call.Return(run)
	return _c
}

// NewQueryClient creates a new instance of QueryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryClient {
	mock := &QueryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
