// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/market/v1beta5/resourcesoffer.proto

package v1beta5

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	v1beta4 "pkg.akt.dev/go/node/types/resources/v1beta4"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ResourceOffer describes resources that provider is offering
// for deployment
type ResourceOffer struct {
	Resources v1beta4.Resources `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources" yaml:"resources"`
	Count     uint32            `protobuf:"varint,2,opt,name=count,proto3" json:"count" yaml:"count"`
}

func (m *ResourceOffer) Reset()         { *m = ResourceOffer{} }
func (m *ResourceOffer) String() string { return proto.CompactTextString(m) }
func (*ResourceOffer) ProtoMessage()    {}
func (*ResourceOffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_90a800b77898768f, []int{0}
}
func (m *ResourceOffer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResourceOffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResourceOffer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResourceOffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceOffer.Merge(m, src)
}
func (m *ResourceOffer) XXX_Size() int {
	return m.Size()
}
func (m *ResourceOffer) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceOffer.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceOffer proto.InternalMessageInfo

func (m *ResourceOffer) GetResources() v1beta4.Resources {
	if m != nil {
		return m.Resources
	}
	return v1beta4.Resources{}
}

func (m *ResourceOffer) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*ResourceOffer)(nil), "akash.market.v1beta5.ResourceOffer")
}

func init() {
	proto.RegisterFile("akash/market/v1beta5/resourcesoffer.proto", fileDescriptor_90a800b77898768f)
}

var fileDescriptor_90a800b77898768f = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0xcc, 0x4e, 0x2c,
	0xce, 0xd0, 0xcf, 0x4d, 0x2c, 0xca, 0x4e, 0x2d, 0xd1, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34,
	0xd5, 0x2f, 0x4a, 0x2d, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x2d, 0xce, 0x4f, 0x4b, 0x4b, 0x2d, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x01, 0x2b, 0xd5, 0x83, 0x28, 0xd5, 0x83, 0x2a, 0x95,
	0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x2b, 0xd0, 0x07, 0xb1, 0x20, 0x6a, 0xa5, 0x74, 0x20, 0xc6,
	0x26, 0x25, 0x16, 0xa7, 0x22, 0x0c, 0x83, 0x1a, 0x6f, 0x82, 0x10, 0x81, 0xa8, 0x56, 0xda, 0xc2,
	0xc8, 0xc5, 0x1b, 0x04, 0x15, 0xf3, 0x07, 0xd9, 0x28, 0x94, 0xc3, 0xc5, 0x09, 0x57, 0x24, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0xa4, 0xae, 0x07, 0xb1, 0x1f, 0x64, 0xa6, 0x1e, 0xc2, 0x04, 0xa8,
	0x99, 0x7a, 0x30, 0xfd, 0xc5, 0x4e, 0xaa, 0x27, 0xee, 0xc9, 0x33, 0xbc, 0xba, 0x27, 0x8f, 0x30,
	0xe1, 0xd3, 0x3d, 0x79, 0x81, 0xca, 0xc4, 0xdc, 0x1c, 0x2b, 0x25, 0xb8, 0x90, 0x52, 0x10, 0x42,
	0x5a, 0x48, 0x9f, 0x8b, 0x35, 0x39, 0xbf, 0x34, 0xaf, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0xd7,
	0x49, 0xf2, 0xd5, 0x3d, 0x79, 0x88, 0xc0, 0xa7, 0x7b, 0xf2, 0x3c, 0x10, 0x8d, 0x60, 0xae, 0x52,
	0x10, 0x44, 0xd8, 0x8a, 0xe5, 0xc5, 0x02, 0x79, 0x46, 0x27, 0xeb, 0x13, 0x8f, 0xe4, 0x18, 0x2f,
	0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18,
	0x6e, 0x3c, 0x96, 0x63, 0x88, 0x52, 0x2c, 0xc8, 0x4e, 0xd7, 0x4b, 0xcc, 0x2e, 0xd1, 0xcb, 0x04,
	0x85, 0x8a, 0x7e, 0x5e, 0x7e, 0x4a, 0x2a, 0x5a, 0x10, 0x27, 0xb1, 0x81, 0xbd, 0x6e, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xd7, 0x65, 0x97, 0x33, 0x81, 0x01, 0x00, 0x00,
}

func (this *ResourceOffer) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResourceOffer)
	if !ok {
		that2, ok := that.(ResourceOffer)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Resources.Equal(&that1.Resources) {
		return false
	}
	if this.Count != that1.Count {
		return false
	}
	return true
}
func (m *ResourceOffer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResourceOffer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResourceOffer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintResourcesoffer(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Resources.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResourcesoffer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintResourcesoffer(dAtA []byte, offset int, v uint64) int {
	offset -= sovResourcesoffer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ResourceOffer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Resources.Size()
	n += 1 + l + sovResourcesoffer(uint64(l))
	if m.Count != 0 {
		n += 1 + sovResourcesoffer(uint64(m.Count))
	}
	return n
}

func sovResourcesoffer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozResourcesoffer(x uint64) (n int) {
	return sovResourcesoffer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ResourceOffer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResourcesoffer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResourceOffer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResourceOffer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResourcesoffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResourcesoffer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResourcesoffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Resources.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResourcesoffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipResourcesoffer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResourcesoffer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipResourcesoffer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowResourcesoffer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResourcesoffer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResourcesoffer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthResourcesoffer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupResourcesoffer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthResourcesoffer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthResourcesoffer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowResourcesoffer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupResourcesoffer = fmt.Errorf("proto: unexpected end of group")
)
