// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/audit/v1/service.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("akash/audit/v1/service.proto", fileDescriptor_767ce8698e34fe92) }

var fileDescriptor_767ce8698e34fe92 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xcc, 0x4e, 0x2c,
	0xce, 0xd0, 0x4f, 0x2c, 0x4d, 0xc9, 0x2c, 0xd1, 0x2f, 0x33, 0xd4, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x03, 0xcb, 0xea, 0x81, 0x65, 0xf5,
	0xca, 0x0c, 0xa5, 0xc4, 0x93, 0xf3, 0x8b, 0x73, 0xf3, 0x8b, 0xf5, 0x73, 0x8b, 0xd3, 0x41, 0x8a,
	0x73, 0x8b, 0xd3, 0x21, 0x0a, 0xa5, 0x24, 0xd0, 0x8c, 0x81, 0xcb, 0x18, 0x35, 0x31, 0x71, 0x31,
	0xfb, 0x16, 0xa7, 0x0b, 0x95, 0x71, 0x89, 0x05, 0x67, 0xa6, 0xe7, 0x05, 0x14, 0xe5, 0x97, 0x65,
	0xa6, 0xa4, 0x16, 0x39, 0x96, 0x94, 0x14, 0x65, 0x26, 0x95, 0x96, 0xa4, 0x16, 0x0b, 0x69, 0xea,
	0xa1, 0xda, 0xa2, 0xe7, 0x5b, 0x9c, 0x8e, 0x5d, 0xa9, 0x94, 0x21, 0xd1, 0x4a, 0x83, 0x52, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x6a, 0xb8, 0x24, 0x5c, 0x52, 0x73, 0x52, 0x4b, 0x52, 0xb1,
	0xd8, 0xac, 0x8d, 0xc5, 0x38, 0x5c, 0x8a, 0xa5, 0x8c, 0x49, 0x50, 0x0c, 0xb3, 0x5d, 0x8a, 0xb5,
	0xe1, 0xf9, 0x06, 0x2d, 0x46, 0x27, 0xb3, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c,
	0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63,
	0x88, 0x92, 0x29, 0xc8, 0x4e, 0xd7, 0x4b, 0xcc, 0x2e, 0xd1, 0x4b, 0x49, 0x2d, 0xd3, 0x4f, 0xcf,
	0xd7, 0xcf, 0xcb, 0x4f, 0x49, 0x85, 0x07, 0x63, 0x12, 0x1b, 0x38, 0x0c, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x0b, 0xb0, 0x08, 0x31, 0xa6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SignProviderAttributes defines a method that signs provider attributes.
	SignProviderAttributes(ctx context.Context, in *MsgSignProviderAttributes, opts ...grpc.CallOption) (*MsgSignProviderAttributesResponse, error)
	// DeleteProviderAttributes defines a method that deletes provider attributes.
	DeleteProviderAttributes(ctx context.Context, in *MsgDeleteProviderAttributes, opts ...grpc.CallOption) (*MsgDeleteProviderAttributesResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SignProviderAttributes(ctx context.Context, in *MsgSignProviderAttributes, opts ...grpc.CallOption) (*MsgSignProviderAttributesResponse, error) {
	out := new(MsgSignProviderAttributesResponse)
	err := c.cc.Invoke(ctx, "/akash.audit.v1.Msg/SignProviderAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteProviderAttributes(ctx context.Context, in *MsgDeleteProviderAttributes, opts ...grpc.CallOption) (*MsgDeleteProviderAttributesResponse, error) {
	out := new(MsgDeleteProviderAttributesResponse)
	err := c.cc.Invoke(ctx, "/akash.audit.v1.Msg/DeleteProviderAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SignProviderAttributes defines a method that signs provider attributes.
	SignProviderAttributes(context.Context, *MsgSignProviderAttributes) (*MsgSignProviderAttributesResponse, error)
	// DeleteProviderAttributes defines a method that deletes provider attributes.
	DeleteProviderAttributes(context.Context, *MsgDeleteProviderAttributes) (*MsgDeleteProviderAttributesResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SignProviderAttributes(ctx context.Context, req *MsgSignProviderAttributes) (*MsgSignProviderAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignProviderAttributes not implemented")
}
func (*UnimplementedMsgServer) DeleteProviderAttributes(ctx context.Context, req *MsgDeleteProviderAttributes) (*MsgDeleteProviderAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProviderAttributes not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SignProviderAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSignProviderAttributes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SignProviderAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akash.audit.v1.Msg/SignProviderAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SignProviderAttributes(ctx, req.(*MsgSignProviderAttributes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteProviderAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteProviderAttributes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteProviderAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akash.audit.v1.Msg/DeleteProviderAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteProviderAttributes(ctx, req.(*MsgDeleteProviderAttributes))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "akash.audit.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignProviderAttributes",
			Handler:    _Msg_SignProviderAttributes_Handler,
		},
		{
			MethodName: "DeleteProviderAttributes",
			Handler:    _Msg_DeleteProviderAttributes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "akash/audit/v1/service.proto",
}
