name: release
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - name: Setup env
        uses: HatsuneMiku3939/direnv-action@v1
      - run: |
          toolchain=$(cat go.mod | grep toolchain | cut -d ' ' -f 2 | sed 's/go*//')
          echo "GOTOOLCHAIN=go${toolchain}" >> $GITHUB_ENV
          echo "GOVERSION=${toolchain}" >> $GITHUB_ENV
          echo "GOROOT=/opt/hostedtoolcache/go/${toolchain}/x64" >> $GITHUB_ENV
      - uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GOVERSION }}"
      - name: get version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Install git-chglog
        run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@${{ env.GIT_CHGLOG_VERSION }}
      - name: Generate changelog
        run: make changelog
      - uses: cb80/delrel@latest
        with:
          tag: v${{ env.RELEASE_TAG}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.md
