name: shellcheck

on:
  push:
    paths:
      - "**.sh"
      - ".github/workflows/shellcheck.yaml"

jobs:
  shellcheck-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - name: Setup env
        uses: HatsuneMiku3939/direnv-action@v1
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - run: make shellcheck
