name: tests
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow
      - name: Setup env
        uses: HatsuneMiku3939/direnv-action@v1
      - run: |
          toolchain=$(./script/tools.sh gotoolchain | sed 's/go*//')
          echo "GOVERSION=${toolchain}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOVERSION }}"
      - run: SUB_TESTS=go TEST_RACE=1 make test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow
      - name: Setup env
        uses: HatsuneMiku3939/direnv-action@v1
      - run: |
          toolchain=$(./script/tools.sh gotoolchain | sed 's/go*//')
          echo "GOVERSION=${toolchain}" >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.1
          cache: npm
          cache-dependency-path: ts/package-lock.json
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOVERSION }}"
      - run: make test-coverage
      - name: Upload GO Test Coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload TS Test Coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./ts/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
