name: golang
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow
      - name: Setup env
        uses: HatsuneMiku3939/direnv-action@v1
      - run: |
          toolchain=$(./script/tools.sh gotoolchain | sed 's/go*//')
          echo "GOVERSION=${toolchain}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOVERSION }}"
      - run: TEST_RACE=1 make test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow
      - name: Setup env
        uses: HatsuneMiku3939/direnv-action@v1
      - run: |
          toolchain=$(./script/tools.sh gotoolchain | sed 's/go*//')
          echo "GOVERSION=${toolchain}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOVERSION }}"
      - run: make test-coverage
      - uses: codecov/codecov-action@v3
